### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by avafinger** [friendlyarm/h5_lichee#1]
There is a Makefile issue while doing a clean i can not figure out how to fix.
Doing  a clean makefile enters infinite loop and can't be finished, here is the issue:

### GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'scripts/Makefile.clean'...
Reading makefile '/arm/ubuntu/h5/nanopi-neo2/lichee/linux-3.10/drivers/video/sunxi/disp2/disp/Makefile' (search path) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de/Makefile' (search path) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...
Reading makefile 'drivers/video/sunxi/disp2/disp/de//Makefile' (search path) (don't care) (no ~ expansion)...

**Comment by avafinger** [comment]
I have rewritten the Makefile, when i  able to test the Image on the board i add the patch here or i make a pull request.

**Comment by wuweidong0107** [comment]
Nice

**Comment by avafinger** [comment]
I think this would fix that.
[neo2-bsp-clean-all.patch.tar.gz](https://github.com/friendlyarm/h5_lichee/files/1425097/neo2-bsp-clean-all.patch.tar.gz)
